DROP TABLE IF EXISTS STUDENTS;  
CREATE TABLE STUDENTS (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
name VARCHAR(50) NOT NULL,  
subject_1 VARCHAR(50) NOT NULL,
subject_2 VARCHAR(50) NOT NULL,
subject_3 VARCHAR(50) NOT NULL,
subject_4 VARCHAR(50) NOT NULL,
subject_5 VARCHAR(50) NOT NULL,
passpercentage VARCHAR(50) NOT NULL,
active boolean(1) DEFAULT TRUE
);  